- id: '1596516365501'
  alias: 'Alarm: Set Home'
  description: ''
  trigger:
  - entity_id: counter.alarm
    from: '0'
    platform: state
    to: '30'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: pending
  action:
  - data: {}
    entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_arm_home
  - data:
      value: 30
    entity_id: counter.alarm_gauge_max
    service: counter.configure
  mode: single
  
- id: '1596517792508'
  alias: 'Alarm: Set Away'
  description: ''
  trigger:
  - entity_id: counter.alarm
    from: '0'
    platform: state
    to: '60'
  condition: []
  action:
  - data: {}
    entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_arm_away
  - data:
      value: 60
    entity_id: counter.alarm_gauge_max
    service: counter.configure
  mode: single
  
- id: '1596518008634'
  alias: 'Alarm: Clear Counter'
  description: ''
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    from: pending
    platform: state
  condition: []
  action:
  - data:
      initial: 0
      value: 0
    entity_id: counter.alarm
    service: counter.configure
  mode: single
  
- id: '1596519091795'
  alias: 'Alarm: Set Counter - Away Trigger'
  description: ''
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    from: armed_away
    platform: state
    to: pending
  condition: []
  action:
  - data:
      value: 30
    entity_id: counter.alarm
    service: counter.configure
  - data:
      initial: 30
      value: 30
    entity_id: counter.alarm_gauge_max
    service: counter.configure
  mode: single
  
- id: '1596558833265'
  alias: 'Alarm: Start Alarm Counter'
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /1
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: pending
  action:
  - data:
      entity_id: counter.alarm
    service: counter.decrement
  mode: single
  
- id: '1596641872770'
  alias: 'Alarm: Reset View Keypad Boolean'
  description: ''
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    from: armed_home
    platform: state
  - entity_id: alarm_control_panel.ha_alarm
    from: armed_away
    platform: state
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.alarm_view_keypad
    service: input_boolean.turn_off
  mode: single
