# Alarm Config - manual_mqtt or manual platform should perform the same
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    code: 'xxxx'
    code_arm_required: false
    pending_time: 0
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 0
    armed_home:
      pending_time: 30
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30

#Counter for countdown
counter:
  alarm:

#Input Boolean
input_boolean:
  alarm_triggered_pending:
  alarm_view_keypad: